name: Checkov

on:
  push:
    branches: ["main"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          soft_fail: true

      - name: Create Checkov Comment
        uses: actions/github-script@v5
        if: always()
        env:
          CHECKOV_PR_TOKEN: ${{ secrets.CHECKOV_PR_TOKEN }}
        with:
          script: |
            const output = require('child_process').execSync('checkov -d .').toString()
            const octokit = require('@octokit/rest')()
            octokit.authenticate({
              type: 'token',
              token: process.env.CHECKOV_PR_TOKEN
            })
            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Checkov Results:\n```\n' + output + '\n```'
            })
