name: Checkov

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Octokit
        run: npm install @octokit/rest

      - name: Checkov GitHub Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: json
          soft_fail: true

      - name: Create Checkov Comment
        uses: actions/github-script@v5
        if: always()
        env:
          CHECKOV_PR_TOKEN: ${{ secrets.CHECKOV_PR_TOKEN }}
        with:
          script: |
            const output = '${{ steps.checkov.outputs.checkov_output }}'
            const octokit = require('@octokit/rest')()
            octokit.authenticate({
              type: 'token',
              token: process.env.CHECKOV_PR_TOKEN
            })
            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Checkov Results:\n```\n' + output + '\n```'
            })
