name: Checkov

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
        env:
          checkov-results: '${{fromJson(steps.checkov.outputs.checkov_results)}}'
      - name: Print Checkov Outputs
        run: echo "${{ steps.checkov.outputs.checkov_results }}" | jq .
      - name: Create Pull Request
        if: steps.checkov.outputs.num_failed > 0
        uses: peter-evans/create-pull-request@v3
        with:
            title: Checkov scan failed
            commit-message: Checkov scan failed
            branch: checkov-failed
            body: |
              The Checkov scan detected the following potential security issues in the Terraform code:
              $(checkov -d /path/to/terraform/directory -o json | jq -r '.results[] | select(.status == "FAILED") | "- " + .check_id + ": " + .check_name')
            token: ${{ secrets.CHECKOV_PR_TOKEN }}
