name: Checkov

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
      - name: Create Pull Request
        if: steps.checkov.outputs.failed == 'true'
        uses: actions/github-script@v4
        with:
        github-token: ${{ secrets.CHECKOV_PR_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Checkov scan failed',
            body: `The Checkov scan detected potential security issues in the Terraform code. Please review the changes and make any necessary fixes. \n\n Failed Checkov check: ${getFailedCheck()}`,
            head: 'checkov-failed',
            base: 'main'
          })
          console.log(`Created pull request ${pullRequest.html_url}`)
          
        env:
        CHECKOV_REPORT: ${{ steps.checkov.outputs.report }}
        
        # Helper function to extract the failed check from the Checkov report
        # This example assumes that the report is in SARIF format
        # and uses the jq command to extract the necessary information
        # You may need to modify this function depending on the format of your report
        run: |
        function getFailedCheck() {
          failedCheck=$(jq '.runs[0].results[] | select(.level == "error") | .ruleId' "${CHECKOV_REPORT}")
          echo "${failedCheck}"
        }
