name: Checkov

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
      - name: Create Pull Request
        if: steps.checkov.outcome == 'failure'
        uses: peter-evans/create-pull-request@v3
        with:
          title: Checkov scan failed
          commit-message: Checkov scan failed
          branch: checkov-failed
          body: |
            The Checkov scan detected potential security issues in the Terraform code. Please review the changes and make any necessary fixes.
          token: ${{ secrets.CHECKOV_PR_TOKEN }}
